spring:
  datasource:
    url: jdbc:mysql://172.16.11.37:3306/simuladores_vehiculos
    username: simuladores
    password: 321-Simula
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

server:
  port: 8081