spring:
  datasource:
    url: jdbc:mysql://srv944.hstgr.io:3306/u836450600_account
    username: u836450600_account
    password: 1*uL|b5|NTI
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

server:
  port: 8081